JFrame(title="Trained Model Runner", size=600x500, defaultCloseOperation=disposeOnClose):
    - JTextField(name=mExperimentText)
    - JButton(name=mOpenExperimentButton, text="Open", onAction=[openExperiment])
    - JPanel(name=mSelectedPanel, groupTitle="Selected Algorithm"):
        - JLabel(name=mSelectedErrorLabel)
        - JTextField(name=mClassifierText, enabled=false, editable=false)
        - JTextField(name=mClassifierParamsText, enabled=false, editable=false)
        - JTextField(name=mAttributeSearchText, enabled=false, editable=false)
        - JTextField(name=mAttributeSearchParamsText, enabled=false, editable=false)
        - JTextField(name=mAttributeEvalText, enabled=false, editable=false)
        - JTextField(name=mAttributeEvalParamsText, enabled=false, editable=false)
        - MigLayout : |
            []                             [grow]
            >"Model Error Estimate: "      mSelectedErrorLabel+*
            >"Classifier: "                mClassifierText+*
            >"Classifier Params: "         mClassifierParamsText+*
            >"Attribute Search: "          mAttributeSearchText+*
            >"Attribute Search Params: "   mAttributeSearchParamsText+*
            >"Attribute Eval: "            mAttributeEvalText+*
            >"Attribute Eval Params: "     mAttributeEvalParamsText+*
    - JPanel(name=mDetailsPanel,groupTitle="Details of Experiment Run that was Selected"):
        - JLabel(name=mSelectedSeedLabel)
        - JLabel(name=mNumEvaluationsLabel)
        - JLabel(name=mNumTimeOutEvaluationsLabel)
        - JLabel(name=mNumMemOutEvaluationsLabel)
        - MigLayout : |
            []                                    [grow]                            []
            >"Selected Model Seed: "              mSelectedSeedLabel+*
            <"Number of evaluations in selected experiment run:"+*  mNumEvaluationsLabel+*
            <"Number of evaluations that timed out:"+*              mNumTimeOutEvaluationsLabel+*
            <"Number of evaluations that exceeded memory limit:"+*  mNumMemOutEvaluationsLabel+*
    - JButton(name=mMakePredictionsButton, text="Make predictions on a dataset", enabled=false, onAction=[openTestingSet,makePredictions])
    - MigLayout : |
        []                                    [grow]                            []
        >"ExperimentFolder: "                 mExperimentText                   mOpenExperimentButton
        >mSelectedPanel+*
        >mDetailsPanel+*
        |mMakePredictionsButton+*
